# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c88f0ec51a5fc25e5756e65014657a840f8313e44b82a42f2e6c98cfcb8c19539baa9f9b45c34e173b29f93720c8886a0693014dce8caa918f4791710e683376

test:
  secret_key_base: 6fe9e01198dddd9afb5ef47ffd703ed8f6bc641bdac3d30e27a6e2f7efc3538a795a70c9f306c4edca9deec8ea5e4fca704e4318dbf96a38fde643ed5b8b6c15

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
